name: Update BNZ Rates

on:
  schedule:
    - cron: "0 17 * * 1,5"   # 17:00 on Monday and Friday
  workflow_dispatch:       # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - name: Run scraper
        run: python scrape_bnz_rates.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update BNZ rates [skip ci]" || echo "No changes to commit"
          git push origin main
